[package]
name = "updater"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.11.3"
crossbeam-channel = "0.5.14"
pgp = "0.14.2"
ring = "0.17.8"
serde = "1.0.217"
serde_json = "1.0.135"
ureq = { version = "2.12.1", features = ["json"] }
