name: Update check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    name: Update
    runs-on: windows-latest

    steps:
      # v4.2.2
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # v4.2.0
      - name: Restore updater
        id: restore-updater
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ./updater.exe
          key: ${{ hashfile(./updater/version) }}

      - name: Build updater
        if: steps.restore-updater.cache-hit != true
        run: |
          cargo build --release --manifest-path '.\updater\Cargo.toml'
          cp '.\updater\target\release\updater.exe' '.'

      # v4.2.0
      - name: Cache updater
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ./updater.exe
          key: ${{ hashfile(./updater/version) }}

      - name: Update
        run: ./updater.exe "'${{ secrets.choco_api_key }}'"
